# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='votes_totale',
            new_name='votes_total',
        ),
    ]
